//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pt.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 GNU GENERAL PUBLIC LICENSE
        ///
        ///Version 3, 29 June 2007
        ///
        ///Copyright ? 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;
        ///
        ///Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.
        ///
        ///Preamble
        ///
        ///The GNU General Public License is a free, copyleft license for software and other kinds of works.
        ///
        ///The licenses for most software and other practical works are designed to take away your freedom to share and change the works. By contrast, the GNU Ge [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GPLv3 {
            get {
                return ResourceManager.GetString("GPLv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] office2007 {
            get {
                object obj = ResourceManager.GetObject("office2007", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &gt;&gt;&gt;2018/1/31 11:20:41 Alpha20
        ///[ADD] import elements mode;_By Gao Mengkai
        ///&gt;&gt;&gt;2018/1/29 11:35:11 Alpha19:
        ///[INTEGRATE] I put the skin files and IrisSkin.dll into the EXE._By Gao Mengkai
        ///[FIX] GNU form&apos;s Select-all;_By Duan Yichen
        ///[FIX] GNU and this form does not have any theme, now fixed;_By Gao Mengkai
        ///&gt;&gt;&gt;2018/1/29 10:20:40 Alpha18:
        ///[ADD] a function of filling in the blank of Z;_By Gao Mengkai
        ///[INTEGRATE] codes;_By Gao Mengkai;_By Gao Mengkai
        ///[FIX] some bugs._By Gao Mengkai
        ///&gt;&gt;&gt;2018/1/26 21:50:49 Alp [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UpdateLog {
            get {
                return ResourceManager.GetString("UpdateLog", resourceCulture);
            }
        }
    }
}
